services:
  next-app-dev:
    build:
      context: .
      target: next
    container_name: next-app-dev
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]