name: Build and Test
run-name: ${{ github.actor }} building and testing the code 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

    
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        browser: ["chrome", "edge"]
    name: Run tests on ${{ matrix.browser }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore cached Node Modules
        id: cache-node-modules-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            node_modules
            /home/runner/.cache/Cypress
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          browser: ${{ matrix.browser }}
          start: npm run dev

      # - name: Run tests
      #   run: npm run e2e:headless

      - name: Save Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}-cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
      - name: Save Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.browser }}-cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
